Issue ck 482
planetarypraxis/smartforests pull request #243
Opened 2022-11-29 12:57 UTC by lowlandjuju

Adds a cookie consent popup for GDPR compliance. 

## Description
- Uses this package: https://github.com/orestbida/cookieconsent
- The cookie consent manages its own consent cookie, plus two cookies from PostHog 

## Motivation and Context
Fixes issue CK-482 (Common Knowledge)

## How Can It Be Tested?
Manually

2022-11-29 15:14 UTC, janbaykara requested changes
This is very nice and neat. I've not tested it but assume you have! Have requested one quick change to the copy, to be a bit more accurate.

2022-11-29 15:14 UTC, janbaykara commented on smartforests/templates/cookie_consent.html
> +                                  description: 'These cookies allow the website to remember the choices you have made in the past',
This isn't quite true. These cookies allow the research team to collect usage data so they can improve the website over time.

2022-11-30 08:07 UTC, lowlandjuju commented on smartforests/templates/cookie_consent.html
> +                                  description: 'These cookies allow the website to remember the choices you have made in the past',
Thanks @janbaykara :pray:  - this is resolved now

2022-11-30 12:14 UTC, janbaykara approved these changes
Ship it!

2022-12-02 16:25 UTC, merged