Use richtext for image captions
planetarypraxis/smartforests pull request #247
Opened 2022-11-30 08:22 UTC by lowlandjuju

Replaces CharBlock with RichTextBlock

2022-11-30 12:16 UTC, janbaykara requested changes

2022-11-30 12:16 UTC, janbaykara commented on logbooks/templates/logbooks/story_blocks/image.html
> +<div class='fs-7 text-grey mt-3 mb-0'>{{ value.caption }}</div>
Ah, one extra thing here. We'll need to use the `richtext` filter to render `value.caption` correctly. [Docs for that here.](https://docs.wagtail.org/en/stable/topics/writing_templates.html#rich-text-filter)

2022-11-30 12:17 UTC, janbaykara requested changes

2022-11-30 12:17 UTC, janbaykara commented on logbooks/models/blocks.py
> +    caption = blocks.RichTextBlock()
We might want to limit the features an editor can add to the rich text. Probably links and basic text formatting but, for example, no embedding images or anything. [Docs on that here.](https://docs.wagtail.org/en/stable/topics/writing_templates.html#rich-text-filter)

2022-12-08 20:12 UTC, janbaykara commented
@lowlandjuju bumping this, just need to add `features=[]` to the Rich Text

2022-12-08 20:21 UTC, lowlandjuju commented
Thanks @janbaykara - latest commit addresses your two comments above :point_up: x

2022-12-12 10:42 UTC, merged